name: prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: update
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_VPS_IP }}
          username: ${{ secrets.PROD_VPS_USER }}
          password: ${{ secrets.PROD_VPS_PASS }}

          script: |
            cd /home/iam-test-music-lib && git pull

            docker-compose -f "docker-compose.prod.yml" up --build -d
